# Generated by Django 4.2.6 on 2023-10-07 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Produto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100, verbose_name="Nome")),
                (
                    "preco",
                    models.DecimalField(
                        decimal_places=4, max_digits=10, verbose_name="Preço"
                    ),
                ),
                ("estoque", models.IntegerField(verbose_name="Quantidade em Estoque")),
            ],
        ),
    ]
